--INSERT INTO usuario (nome, username, password) VALUES ('Anderson Lima', 'msgli34@gmail.com', '$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');
--INSERT INTO usuario (nome, username, password) VALUES ('teste', 'teste', '$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');
--INSERT INTO usuario (nome, username, password) VALUES ('Ananda Muniz', 'ananda', '$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');
--
--INSERT INTO role (role_name) VALUES ('ROLE_OPERATOR');
--INSERT INTO role (role_name) VALUES ('ROLE_ADMIN');
--
--INSERT INTO tb_usuario_role (usuario_id, role_id) VALUES (1, 1);
--INSERT INTO tb_usuario_role (usuario_id, role_id) VALUES (2, 1);
--INSERT INTO tb_usuario_role (usuario_id, role_id) VALUES (2, 2);
--INSERT INTO tb_usuario_role (usuario_id, role_id) VALUES (3, 1);
--INSERT INTO tb_usuario_role (usuario_id, role_id) VALUES (3, 2);
